spring:
    datasource:
        url: jdbc:h2:mem:uaa;DB_CLOSE_DELAY=-1
        username: orderadmin
        password:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

